spring.application.name=order-service-group-2
server.port=${SERVER_PORT:9000}
product-service.base-url=${PRODUCT_SERVICE_BASE_URL:http://localhost:8081}
auth-service.base-url=${AUTH_SERVICE_URL:http://localhost:8080}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}
spring.rabbitmq.host=kebnekaise.lmq.cloudamqp.com
spring.rabbitmq.port=5671
spring.rabbitmq.username=${RABBIT_USERNAME}
spring.rabbitmq.password=${RABBIT_PASSWORD}
spring.rabbitmq.virtual-host=${RABBIT_VIRTUAL_HOST}
spring.rabbitmq.ssl.enabled=true