spring.application.name=order-service-group-2
server.port=${SERVER_PORT:9000}
product-service.base-url=${PRODUCT_SERVICE_BASE_URL:http://localhost:8081}
spring.jpa.hibernate.ddl-auto=update
spring.datasource.url=${DB_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}