name: Build with Maven

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout kod
        uses: actions/checkout@v4

      - name: Sätt upp Java
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'

      - name: Bygg med Maven
        run: mvn clean package

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: birkegard
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: birkegard/order-service-group-2:latest